//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsung_Jellyfin_Installer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samsung_Jellyfin_Installer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Tizen OS version....
        /// </summary>
        public static string CheckTizenOS {
            get {
                return ResourceManager.GetString("CheckTizenOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose release....
        /// </summary>
        public static string ChooseRelease {
            get {
                return ResourceManager.GetString("ChooseRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose TV....
        /// </summary>
        public static string ChooseTV {
            get {
                return ResourceManager.GetString("ChooseTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose version....
        /// </summary>
        public static string ChooseVersion {
            get {
                return ResourceManager.GetString("ChooseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to device....
        /// </summary>
        public static string ConnectingToDevice {
            get {
                return ResourceManager.GetString("ConnectingToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Author CSR....
        /// </summary>
        public static string CreateAuthorCsr {
            get {
                return ResourceManager.GetString("CreateAuthorCsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Distributor CSR with DUID....
        /// </summary>
        public static string CreateDistributorCSR {
            get {
                return ResourceManager.GetString("CreateDistributorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the signed P12 files....
        /// </summary>
        public static string CreateNewCertificates {
            get {
                return ResourceManager.GetString("CreateNewCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install.
        /// </summary>
        public static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed:.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package....
        /// </summary>
        public static string DownloadingPackage {
            get {
                return ResourceManager.GetString("DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was canceled or failed....
        /// </summary>
        public static string FailedAuthCode {
            get {
                return ResourceManager.GetString("FailedAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load releases:.
        /// </summary>
        public static string FailedLoadingReleases {
            get {
                return ResourceManager.GetString("FailedLoadingReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating keypair.
        /// </summary>
        public static string GenKeyPair {
            get {
                return ResourceManager.GetString("GenKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating random password....
        /// </summary>
        public static string GenPassword {
            get {
                return ResourceManager.GetString("GenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation may have failed.
        /// </summary>
        public static string InstallationMaybeFailed {
            get {
                return ResourceManager.GetString("InstallationMaybeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        public static string InstallationSuccessful {
            get {
                return ResourceManager.GetString("InstallationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed on.
        /// </summary>
        public static string InstallationSuccessfulOn {
            get {
                return ResourceManager.GetString("InstallationSuccessfulOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package on device....
        /// </summary>
        public static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device IP or device not found..
        /// </summary>
        public static string InvalidDeviceIp {
            get {
                return ResourceManager.GetString("InvalidDeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My IP is not listed....
        /// </summary>
        public static string IpNotListed {
            get {
                return ResourceManager.GetString("IpNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the device&apos;s IP address:.
        /// </summary>
        public static string IpWindowDescription {
            get {
                return ResourceManager.GetString("IpWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter TV IP.
        /// </summary>
        public static string IpWindowTitle {
            get {
                return ResourceManager.GetString("IpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string lbl_Certifcate {
            get {
                return ResourceManager.GetString("lbl_Certifcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom WGT.
        /// </summary>
        public static string lbl_CustomWgt {
            get {
                return ResourceManager.GetString("lbl_CustomWgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove old Jellyfin.
        /// </summary>
        public static string lbl_DeletePrevious {
            get {
                return ResourceManager.GetString("lbl_DeletePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string lbl_expires {
            get {
                return ResourceManager.GetString("lbl_expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lbl_Language {
            get {
                return ResourceManager.GetString("lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string lbl_Other {
            get {
                return ResourceManager.GetString("lbl_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string lbl_Release {
            get {
                return ResourceManager.GetString("lbl_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember IPs.
        /// </summary>
        public static string lbl_RememberIp {
            get {
                return ResourceManager.GetString("lbl_RememberIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TV.
        /// </summary>
        public static string lbl_SelectTv {
            get {
                return ResourceManager.GetString("lbl_SelectTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lbl_Settings {
            get {
                return ResourceManager.GetString("lbl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string lbl_Version {
            get {
                return ResourceManager.GetString("lbl_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading releases....
        /// </summary>
        public static string LoadingReleases {
            get {
                return ResourceManager.GetString("LoadingReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files to be used in certificate-manager....
        /// </summary>
        public static string MovingP12Files {
            get {
                return ResourceManager.GetString("MovingP12Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found.
        /// </summary>
        public static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring that the output directory exists.
        /// </summary>
        public static string OutputDir {
            get {
                return ResourceManager.GetString("OutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging the wgt file with certificate....
        /// </summary>
        public static string PackagingWgtWithCertificate {
            get {
                return ResourceManager.GetString("PackagingWgtWithCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizen CLI is required but not found. Please install Tizen Studio first..
        /// </summary>
        public static string PleaseInstallTizen {
            get {
                return ResourceManager.GetString("PleaseInstallTizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting to Samsung endpoint....
        /// </summary>
        public static string PostAuthorCSR {
            get {
                return ResourceManager.GetString("PostAuthorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting to first Samsung distributor....
        /// </summary>
        public static string PostFirstDistributorCSR {
            get {
                return ResourceManager.GetString("PostFirstDistributorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting to second Samsung distributor....
        /// </summary>
        public static string PostSecondDistributorCSR {
            get {
                return ResourceManager.GetString("PostSecondDistributorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for use....
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving device address....
        /// </summary>
        public static string RetrievingDeviceAddress {
            get {
                return ResourceManager.GetString("RetrievingDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning network for Samsung TV....
        /// </summary>
        public static string ScanningNetwork {
            get {
                return ResourceManager.GetString("ScanningNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select certificate.
        /// </summary>
        public static string SelectCertificate {
            get {
                return ResourceManager.GetString("SelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select WGT file.
        /// </summary>
        public static string SelectWGT {
            get {
                return ResourceManager.GetString("SelectWGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing Tizen certificate manager....
        /// </summary>
        public static string SettingCertificateManager {
            get {
                return ResourceManager.GetString("SettingCertificateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting CA certificates....
        /// </summary>
        public static string SettingsCaCerts {
            get {
                return ResourceManager.GetString("SettingsCaCerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully obtained authorization code.
        /// </summary>
        public static string SuccessAuthCode {
            get {
                return ResourceManager.GetString("SuccessAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Name could not be found....
        /// </summary>
        public static string TvNameNotFound {
            get {
                return ResourceManager.GetString("TvNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating certificate profile....
        /// </summary>
        public static string UpdatingCertificateProfile {
            get {
                return ResourceManager.GetString("UpdatingCertificateProfile", resourceCulture);
            }
        }
    }
}
